# Generated by Django 5.2.11 on 2026-02-27 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_delivered_message_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='chat_messag_chat_id_bc1dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
    ]
