# Generated by Django 5.2.11 on 2026-03-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_chat_messag_chat_id_bc1dbb_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
