# Generated by Django 5.2.11 on 2026-03-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_options'),
        ('contact', '0002_alter_contact_contact_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
